# Generated by Django 5.2.7 on 2026-03-23 19:08

import apps.users.validators.cpf
import apps.users.validators.user_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[apps.users.validators.user_fields.validate_birth_date]),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF opcional para cenarios academicos e demonstracoes.', max_length=14, null=True, unique=True, validators=[apps.users.validators.cpf.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[apps.users.validators.user_fields.validate_phone]),
        ),
    ]
